name: Test on Release

on:
  push:
    branches:
      - main
      - develop
      - storybook
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || endsWith(github.ref, '/storybook'))
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
